### ISSUE TITLE
An exception when akka-persistence-mongo work with AKKA cluster sharding

### ISSUE THREAD

**Issue by redlion99** [scullxbones/akka-persistence-mongo#106]
This exception occurs when the region coordinator try to recover from mongo persistence.

23:24:40.177 [collector-akka.actor.default-dispatcher-3] WARN  a.persistence.journal.ReplayFilter - Invalid replayed event [2] in wrong order from writer [d8408a83-17d8-4a9c-990d-35afff9ddcac] with persistenceId [/sharding/DeviceRegionCoordinator]
23:24:40.178 [collector-akka.actor.default-dispatcher-3] WARN  a.persistence.journal.ReplayFilter - Invalid replayed event [1] in wrong order from writer [d8408a83-17d8-4a9c-990d-35afff9ddcac] with persistenceId [/sharding/DeviceRegionCoordinator]
23:24:40.181 [collector-akka.actor.default-dispatcher-3] ERROR a.c.s.PersistentShardCoordinator - Exception in receiveRecover when replaying event type [akka.cluster.sharding.ShardCoordinator$Internal$ShardHomeAllocated] with sequence number [3] for persistenceId [/sharding/DeviceRegionCoordinator].
java.lang.IllegalArgumentException: requirement failed: Region Actor[akka://collector/system/sharding/DeviceRegion#-384370143] not registered: State(Map(),Map(),Set(),Set(),false)
	at scala.Predef$.require(Predef.scala:219) ~[scala-library-2.11.7.jar:na]
	at akka.cluster.sharding.ShardCoordinator$Internal$State.updated(ShardCoordinator.scala:289) ~[akka-cluster-sharding_2.11-2.4.2.jar:na]
	at akka.cluster.sharding.PersistentShardCoordinator$$anonfun$receiveRecover$1.applyOrElse(ShardCoordinator.scala:753) ~[akka-cluster-sharding_2.11-2.4.2.jar:na]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at akka.persistence.Eventsourced$$anon$3$$anonfun$1.applyOrElse(Eventsourced.scala:461) ~[akka-persistence_2.11-2.4.2.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.cluster.sharding.PersistentShardCoordinator.akka$persistence$Eventsourced$$super$aroundReceive(ShardCoordinator.scala:719) ~[akka-cluster-sharding_2.11-2.4.2.jar:na]
	at akka.persistence.Eventsourced$$anon$4.stateReceive(Eventsourced.scala:505) ~[akka-persistence_2.11-2.4.2.jar:na]
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:173) ~[akka-persistence_2.11-2.4.2.jar:na]
	at akka.cluster.sharding.PersistentShardCoordinator.aroundReceive(ShardCoordinator.scala:719) ~[akka-cluster-sharding_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]

**Comment by scullxbones** [comment]
That's strange, I use cluster sharding in production without these issues. I'm pretty sure I'm not alone either.

I need a lot more information to get an understanding.  Is there any more information that you can provide?  Like which driver, which version, is it a regression, is it easily reproducible, are there other log messages or errors from the driver, what does the problematic document in the collection look like, etc.

**Comment by redlion99** [comment]
It's easily reproducible, the error doesn't occur when I use  inmem journal plugin

Here is the driver I'm using 
<img width="525" alt="2016-03-16 4 23 57" src="https://cloud.githubusercontent.com/assets/936350/13806022/dac2a664-eb93-11e5-94f2-f1f35f41b823.png">
<img width="405" alt="2016-03-16 4 24 08" src="https://cloud.githubusercontent.com/assets/936350/13806023/db1c1794-eb93-11e5-8daa-3de28b5ba73f.png">

Here is the document:
<img width="1274" alt="2016-03-16 4 25 30" src="https://cloud.githubusercontent.com/assets/936350/13806026/dd74b6cc-eb93-11e5-86e6-f197f08289a8.png">

**Comment by scullxbones** [comment]
Still need more to be able to duplicate this.  Remember I have no access to your system, environment, etc.  Can you give me all the background information on versions of plugin, mongo, akka?  If there's anything else you think I might need to duplicate, please let me know what it is.

I wonder if you're missing an index, although they should be created every time.  Can you run getIndices on the collection and attach the output to the ticket?

Also please attach the output of your mongo query as something I can copy and paste into a test case.

**Comment by scullxbones** [comment]
Closing due to inactivity - please re-open if the issue persists.
