### ISSUE TITLE
Enable SSL support (with ReactiveMongo 0.11.14)

### ISSUE THREAD

**Issue by epot** [scullxbones/akka-persistence-mongo#121]
It seems ReactiveMongo now supports SSL (since version 0.11.14), but I still get a:
Some options were ignored because they are not supported (yet): ssl
when setting a mongo uri with SSL support.

I guess this is because the way to initialize the connection has to be changed. Is it planned to update this plugin to support SSL as well ? Am I missing something ?

**Comment by epot** [comment]
Actually I just read in the doc that it is incompatible with ReactiveMongo > 0.11.9. Any plan to overcome this limitation in the near future ?

**Comment by scullxbones** [comment]
Hi @epot - there's an open ticket #105 to make changes to support newer versions of rxmongo.  The plugin hasn't been verified against versions beyond 0.11.9 as the test suite fails in strange ways.  I am waiting for the reactive mongo driver development to stabilize before getting back into that ticket.

**Comment by epot** [comment]
Excellent, thanks ! Do you want me to close this one ?

**Comment by scullxbones** [comment]
Hi - no, it can be a reminder to integration test SSL after #105 is fixed.

**Comment by scullxbones** [comment]
Version `1.3.3` is released which supports `0.11.14`.  I haven't tested with an SSL server yet.

**Comment by scullxbones** [comment]
erm `1.3.4` was the correct release.  Let me know if SSL is now working for you.

Thanks!

**Comment by epot** [comment]
I will try as soon as I find some free time, sorry for the delay !

**Comment by epot** [comment]
I just tried with the latest version (1.3.5) and get the same error:
2016-10-31 09:17:43,234 [WARN] - reactivemongo.api.MongoDriver - Some options were ignored because they are not supported (yet): ssl
2016-10-31 09:17:43,235 [INFO] - reactivemongo.api.MongoDriver - [Supervisor-1] Creating connection: Connection-3
2016-10-31 09:17:47,284 [ERROR] - acute3d.scheduler.master.Master - Persistence failure when replaying events for persistenceId [master]. Last known sequence number [0]
java.util.concurrent.TimeoutException: Futures timed out after [4 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[scala-library-2.11.8.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) ~[scala-library-2.11.8.jar:na]
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190) ~[scala-library-2.11.8.jar:na]
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53) ~[scala-library-2.11.8.jar:na]
        at scala.concurrent.Await$.result(package.scala:190) ~[scala-library-2.11.8.jar:na]
        at akka.contrib.persistence.mongodb.RxMongoDriver.wait(RxMongoPersistenceExtension.scala:85) ~[akka-persistence-mongo-rxmongo_2.11-1.3.5.jar:1.3.5]
        at akka.contrib.persistence.mongodb.RxMongoDriver.akka$contrib$persistence$mongodb$RxMongoDriver$$unauthenticatedConnection$lzycompute(RxMongoPersistenceExtension.scala:66) ~[akka-persistence-mongo-rxmongo_2.11-1.3.5.jar:1.3.5]

I tried with ReactiveMongo 0.12.0 and 0.11.14, same issue.

**Comment by epot** [comment]
Actually, it is probably not a akka-persistence-mongo issue anymore. It looks like ReactiveMongo is parsing the connection string and is expecting a "sslEnabled=true" and not "ssl=true" (which is the standard according to mongo doc). I am having other trouble if I change that, but they seem to be within reactive mongo. It means I guess this ticket can be closed.

**Comment by epot** [comment]
I confirm this has been closed. This plugin is not compatible with Microsoft Azure MongoDB driver for Document DB, but the problem lies on Azure side...

**Comment by scullxbones** [comment]
Ok - understood.  Thank you for updating & closing!
