### ISSUE TITLE
Error message "Sort exceeded memory limit of 104857600 bytes" when creating PersistenceActor

### ISSUE THREAD

**Issue by thjaeckle** [scullxbones/akka-persistence-mongo#136]
Hi.
We're getting following Exception when instantiating a PersistenceActor (using version 1.2.5 of akka-persistence-mongo):

```
akka.actor.ActorInitializationException: akka://things-cluster/user/thingsRoot/things/StreamSupervisor-0/flow-655798-1-actorPublisherSource: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:174)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1_aroundBody2(ActorCell.scala:461)
	at akka.actor.ActorCell$AjcClosure3.run(ActorCell.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at akka.kamon.instrumentation.ActorSystemMessageInstrumentation$$anonfun$aroundSystemMessageInvoke$1.apply(ActorSystemMessageInstrumentation.scala:34)
	at kamon.trace.Tracer$.withContext(TracerModule.scala:58)
	at akka.kamon.instrumentation.ActorSystemMessageInstrumentation.aroundSystemMessageInvoke(ActorSystemMessageInstrumentation.scala:34)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:1)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.mongodb.MongoCommandException: Command failed with error 16819: 'Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.' on server mongodb-server.ourhost:30000. The full response is { "ok" : 0.0, "errmsg" : "Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.", "code" : 16819 }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:112)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:227)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:223)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:239)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:223)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:65)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1377)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1347)
	at com.mongodb.casbah.MongoCollectionBase$class.aggregate(MongoCollection.scala:710)
	at com.mongodb.casbah.MongoCollection.aggregate(MongoCollection.scala:1106)
	at com.mongodb.casbah.MongoCollectionBase$class.aggregate(MongoCollection.scala:685)
	at com.mongodb.casbah.MongoCollection.aggregate(MongoCollection.scala:1106)
	at akka.contrib.persistence.mongodb.SequenceNumbersOfPids.initialCursor(CrCasbahPersistenceReadJournaller.scala:107)
	at akka.contrib.persistence.mongodb.SequenceNumbersOfPids.initialCursor(CrCasbahPersistenceReadJournaller.scala:98)
	at akka.contrib.persistence.mongodb.SyncActorPublisher$class.preStart(MongoReadJournal.scala:201)
	at akka.contrib.persistence.mongodb.SequenceNumbersOfPids.preStart(CrCasbahPersistenceReadJournaller.scala:98)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:489)
	at akka.contrib.persistence.mongodb.SequenceNumbersOfPids.akka$stream$actor$ActorPublisher$$super$aroundPreStart(CrCasbahPersistenceReadJournaller.scala:98)
	at akka.stream.actor.ActorPublisher$class.aroundPreStart(ActorPublisher.scala:338)
	at akka.contrib.persistence.mongodb.SequenceNumbersOfPids.aroundPreStart(CrCasbahPersistenceReadJournaller.scala:98)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	... 15 common frames omitted
```

I currently cannot see for which specific persistenceIds this is happening, could be that those are PersistenceActor with a lot of events in their journal.

Would it be an option to set the "allowDiskUse:true" to the query made there? Or is this just fighting 	symptoms?

**Comment by thjaeckle** [comment]
Aah, first think then post.
Sorry, I just realized that the "SequenceNumbersOfPids" is our own ReadJournal query.

Nothing wrong in akka-persistence-mongo.

Sorry again
