### ISSUE TITLE
Persistence failure when replaying events for persistenceId

### ISSUE THREAD

**Issue by gorbenkoya** [scullxbones/akka-persistence-mongo#153]
Hi, guys. I got such exception on prod in job processor service

```[Supervisor-1] Creating connection: Connection-2
 [Supervisor-1/Connection-2] Starting the MongoDBSystem akka://reactivemongo/user/Connection-2
 Persistence failure when replaying events for persistenceId [master]. Last known sequence number [0]
java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at akka.contrib.persistence.mongodb.RxMongoDriver.wait(RxMongoPersistenceExtension.scala:86)
	at akka.contrib.persistence.mongodb.RxMongoDriver.akka$contrib$persistence$mongodb$RxMongoDriver$$unauthenticatedConnection$lzycompute(RxMongoPersistenceExtension.scala:67)
	at akka.contrib.persistence.mongodb.RxMongoDriver.akka$contrib$persistence$mongodb$RxMongoDriver$$unauthenticatedConnection(RxMongoPersistenceExtension.scala:67)
	at akka.contrib.persistence.mongodb.RxMongoDriver$$anonfun$connection$1.apply(RxMongoPersistenceExtension.scala:77)
	at akka.contrib.persistence.mongodb.RxMongoDriver$$anonfun$connection$1.apply(RxMongoPersistenceExtension.scala:77)
	at scala.Option.fold(Option.scala:158)
	at akka.contrib.persistence.mongodb.RxMongoDriver.connection$lzycompute(RxMongoPersistenceExtension.scala:77)
	at akka.contrib.persistence.mongodb.RxMongoDriver.connection(RxMongoPersistenceExtension.scala:75)
	at akka.contrib.persistence.mongodb.RxMongoDriver.db(RxMongoPersistenceExtension.scala:192)
	at akka.contrib.persistence.mongodb.RxMongoDriver.collection(RxMongoPersistenceExtension.scala:194)
	at akka.contrib.persistence.mongodb.RxMongoDriver.collection(RxMongoPersistenceExtension.scala:48)
	at akka.contrib.persistence.mongodb.MongoPersistenceDriver.getSnaps(MongoPersistence.scala:183)
	at akka.contrib.persistence.mongodb.RxMongoSnapshotter.snaps(RxMongoSnapshotter.scala:78)
	at akka.contrib.persistence.mongodb.RxMongoSnapshotter.findYoungestSnapshotByMaxSequence(RxMongoSnapshotter.scala:24)
	at akka.contrib.persistence.mongodb.RxMongoPersistenceExtension$Configured$$anon$2.akka$contrib$persistence$mongodb$MongoPersistenceSnapshotFailFast$$super$findYoungestSnapshotByMaxSequence(RxMongoPersistenceExtension.scala:260)
	at akka.contrib.persistence.mongodb.MongoPersistenceSnapshotFailFast$$anonfun$findYoungestSnapshotByMaxSequence$1.apply(MongoSnapshots.scala:91)
	at akka.contrib.persistence.mongodb.MongoPersistenceSnapshotFailFast$$anonfun$findYoungestSnapshotByMaxSequence$1.apply(MongoSnapshots.scala:91)

```

Looks like code fails on auth wait future. Just looked into 
https://github.com/scullxbones/akka-persistence-mongo/blob/master/rxmongo/src/main/scala/akka/contrib/persistence/mongodb/RxMongoPersistenceExtension.scala
and found 

```  
implicit val waitFor: FiniteDuration = 10.seconds

  private[this] lazy val unauthenticatedConnection: MongoConnection = wait {
    // create unauthenticated connection, there is no direct way to wait for authentication this way
    // plus prevent sending double authentication (initial authenticate and our explicit authenticate)
    driver.connection(parsedURI = parsedMongoUri.copy(authenticate = None))
      .database(name = dbName, failoverStrategy = failoverStrategy)(system.dispatcher)
      .map(_.connection)(system.dispatcher)
  }

  private[mongodb] lazy val connection: MongoConnection =
    // now authenticate explicitly and wait for confirmation
    parsedMongoUri.authenticate.fold(unauthenticatedConnection) { auth =>
      waitForAuthentication(unauthenticatedConnection, auth)
    }

  private[this] def waitForAuthentication(conn: MongoConnection, auth: Authenticate): MongoConnection = {
    wait(conn.authenticate(auth.db, auth.user, auth.password))
    conn
  }
```

I was trying to override 10 sec implicit value but no success. My config file looks like this 
```
akka {

  actor.provider = "akka.cluster.ClusterActorRefProvider"
  actor.warn-about-java-serializer-usage = off

  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"

  log-dead-letters = off

  remote {
    netty.tcp.port = 0
    netty.tcp.hostname = 127.0.0.1
    log-remote-lifecycle-events = off
  }

    cluster {
      seed-nodes = [
        "akka.tcp://ClusterSystem@127.0.0.1:2551", "akka.tcp://ClusterSystem@127.0.0.1:2555"]

      # auto-down-unreachable-after = 10s
      metrics.enabled=off
    }

    extensions = ["akka.cluster.pubsub.DistributedPubSub", "akka.cluster.client.ClusterClientReceptionist"]

    persistence {
      journal.plugin = "akka-contrib-mongodb-persistence-journal"
      snapshot-store.plugin = "akka-contrib-mongodb-persistence-snapshot"
      journal.leveldb.native = off
    }

  }

akka.contrib.persistence.mongodb.mongo.mongouri = "mongodb://localhost:27017/aidp-journal-db"
akka.contrib.persistence.mongodb.mongo.journal-wtimeout = 30s
akka.contrib.persistence.mongodb.mongo.journal-fsync = false
akka.contrib.persistence.mongodb.mongo.snaps-wtimeout = 30s
akka.contrib.persistence.mongodb.mongo.snaps-fsync = false
akka.contrib.persistence.mongodb.mongo.breaker.maxTries = 10
akka.contrib.persistence.mongodb.mongo.breaker.timeout.call = 30s
akka.contrib.persistence.mongodb.mongo.breaker.timeout.reset = 30s

```
Mongo DB works fine without any issues, looks like the issue in small duration
Please advice, thanks in advance

**Comment by scullxbones** [comment]
Hi @gorbenkoya -

- Yes it's true, there is no way to override the connection wait time of `10 seconds`
- From the stack trace the timeout is occurring in the `unauthenticatedConnection` block
- `10 seconds` is an extremely long time to allow for mongodb to connect - I believe there may be an issue in the configuration or possibly a firewall in the way.  You should use the configured URL to test `mongodb://localhost:27017/aidp-journal-db` from the server that is having the issue.  The mongo client should understand a `mongodb://` url

**Comment by gorbenkoya** [comment]
Thanks, it was the issue with local DNS server in DCOS, so connect method hangs more than 10 sec.
