### ISSUE TITLE
`Not authorized to query` error despite successful login

### ISSUE THREAD

**Issue by Hajto** [scullxbones/akka-persistence-mongo#161]
I have encountered following error. Login credentials are for sure correct. I use mongolab hosted db.

```
com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized on storage-db to execute command { find: "akka_persistence_snaps", filter: { $and: [ { pid: "user-test" }, { sn: { $lte: 9223372036854775807 } }, { ts: { $lte: 9223372036854775807 } } ] }, sort: { sn: -1, ts: -1 }, limit: 1 }' on server ds161042.mlab.com:61042
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:492) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:482) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:239) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:482) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:79) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.Mongo.execute(Mongo.java:772) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.Mongo$2.execute(Mongo.java:759) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:851) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.DBCursor.hasNext(DBCursor.java:152) ~[mongo-java-driver-3.2.2.jar:na]
	at com.mongodb.casbah.MongoCursorBase.hasNext(MongoCursor.scala:73) ~[casbah-core_2.12-3.1.1.jar:3.1.1]
	at com.mongodb.casbah.MongoCursorBase.hasNext$(MongoCursor.scala:73) ~[casbah-core_2.12-3.1.1.jar:3.1.1]
	at com.mongodb.casbah.MongoCursor.hasNext(MongoCursor.scala:487) ~[casbah-core_2.12-3.1.1.jar:3.1.1]
	at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:144) ~[scala-library-2.12.0.jar:na]
	at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:132) ~[scala-library-2.12.0.jar:na]
	at com.mongodb.casbah.MongoCursor.collectFirst(MongoCursor.scala:487) ~[casbah-core_2.12-3.1.1.jar:3.1.1]
	at akka.contrib.persistence.mongodb.CasbahPersistenceSnapshotter.$anonfun$findYoungestSnapshotByMaxSequence$1(CasbahPersistenceSnapshotter.scala:84) ~[akka-persistence-mongo-casbah_2.12-2.0.3.jar:2.0.3]
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653) ~[scala-library-2.12.0.jar:na]
	at scala.util.Success.$anonfun$map$1(Try.scala:251) ~[scala-library-2.12.0.jar:na]
	at scala.util.Success.map(Try.scala:209) ~[scala-library-2.12.0.jar:na]
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287) ~[scala-library-2.12.0.jar:na]
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29) ~[scala-library-2.12.0.jar:na]
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29) ~[scala-library-2.12.0.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[scala-library-2.12.0.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.12-2.5.3.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91) ~[akka-actor_2.12-2.5.3.jar:na]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) ~[scala-library-2.12.0.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81) ~[scala-library-2.12.0.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91) ~[akka-actor_2.12-2.5.3.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38) ~[akka-actor_2.12-2.5.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_112]
```

**Comment by Hajto** [comment]
I had similar issues before they were connected with authentication method.

**Comment by scullxbones** [comment]
Hi @Hajto - 

Which series of the plugin are you using?  `0.x`, `1.x`, `2.x`?

We had one issue in the past that I remember where a user had their user information in a different database than the one they connected to for data (I think it was `admin`).  I haven't used mongolab personally, do you know where the user authorization information is stored?

I think that ticket was #67

**Comment by Hajto** [comment]
Yes that was the case. When I specified the DB explicitly the issue is gone.

**Comment by scullxbones** [comment]
> When I specified the DB explicitly the issue is gone.

Great - can I close this issue as resolved?
