### ISSUE TITLE
Runtime error with reactivemongo

### ISSUE THREAD

**Issue by enp0s23** [scullxbones/akka-persistence-mongo#229]
I add persisance plugin as this: 

```scala
libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-persistence" % "2.5.20",
  "com.typesafe.akka" %% "akka-persistence-typed" % "2.5.20",
  "com.typesafe.akka" %% "akka-stream" % "2.5.20",

  "ch.qos.logback" % "logback-classic" % "1.2.3",
  "com.typesafe.akka" %% "akka-slf4j" % "2.5.20",

  "com.github.scullxbones" %% "akka-persistence-mongo-rxmongo" % "2.2.4",

  "org.reactivemongo" %% "reactivemongo" % "0.16.5",
  "org.reactivemongo" %% "reactivemongo-akkastream" % "0.16.5",
  "org.reactivemongo" %% "reactivemongo-bson" % "0.16.5",
  "org.reactivemongo" %% "reactivemongo-bson-macros" % "0.16.5",
}
```

And, on start application, i got these runtime exceptions:
```
java.lang.ClassNotFoundException:
reactivemongo.io.netty.channel.kqueue.KQueueSocketChannel

java.lang.ClassNotFoundException: reactivemongo.io.netty.channel.epoll.EpollSocketChannel

// and app fails with 

java.lang.NoSuchMethodError: reactivemongo.api.collections.bson.BSONCollection.insert(ZLreactivemongo/api/commands/GetLastError;Ljava/lang/Object;)Lreactivemongo/api/collections/InsertOps$InsertBuilder;
	at akka.contrib.persistence.mongodb.RxMongoJournaller.$anonfun$doBatchAppend$2(RxMongoJournaller.scala:84)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It seems that some kind of dependence is missing, but which one?

I try this (unsuccessfully): 

```scala
 "io.netty" % "netty-buffer" % "4.1.17.Final",
 "io.netty" % "netty-transport" % "4.1.17.Final",
 "io.netty" % "netty-handler" % "4.1.17.Final",
```

In [build.sbt](https://github.com/scullxbones/akka-persistence-mongo/blob/master/build.sbt) of project, there seems to be no mention of netty in `akka-persistence-mongo-rxmongo` definition.

**Comment by scullxbones** [comment]
Hi @enp0s23 -

```
NoSuchMethodError reactivemongo.api.collections.bson.BSONCollection.insert(ZLreactivemongo/api/commands/GetLastError;Ljava/lang/Object;)Lreactivemongo/api/collections/InsertOps$InsertBuilder;
```

This ^ sounds like a backward incompatibility in `rxmongo`.  Try going back in rxm versions towards `0.16.0`, and let me know how it goes!

**Comment by enp0s23** [comment]
Thank, I change version of rxmongo to 0.16.0, and it fix problem.
