### ISSUE TITLE
Default journal plugin is not configured.

### ISSUE THREAD

**Issue by nmolenaar** [scullxbones/akka-persistence-mongo#243]
Hey guys,

Since the convertion from akka persistence to akka typed persistence im getting the following error.

```
[info]   java.lang.IllegalArgumentException: Default journal plugin is not configured, see 'reference.conf'
[info]   at akka.persistence.Persistence$.verifyPluginConfigIsDefined(Persistence.scala:193)
[info]   at akka.persistence.typed.internal.EventSourcedSettings$.defaultJournalPluginId$1(EventSourcedSettings.scala:57)
[info]   at akka.persistence.typed.internal.EventSourcedSettings$.journalConfigFor(EventSourcedSettings.scala:61)
[info]   at akka.persistence.typed.internal.EventSourcedSettings$.apply(EventSourcedSettings.scala:39)
[info]   at akka.persistence.typed.internal.EventSourcedSettings$.apply(EventSourcedSettings.scala:22)
[info]   at akka.persistence.typed.internal.EventSourcedBehaviorImpl.apply(EventSourcedBehaviorImpl.scala:83)
[info]   at akka.actor.typed.Behavior$.start(Behavior.scala:331)
[info]   at akka.actor.testkit.typed.internal.BehaviorTestKitImpl.<init>(BehaviorTestKitImpl.scala:36)
[info]   at akka.actor.testkit.typed.scaladsl.BehaviorTestKit$.apply(BehaviorTestKit.scala:22)
[info]   at akka.actor.testkit.typed.scaladsl.BehaviorTestKit$.apply(BehaviorTestKit.scala:25)
```

I've added the 2 lines to the application.conf. 
```
akka.persistence.journal.plugin = "akka-contrib-mongodb-persistence-journal"
akka.persistence.snapshot-store.plugin = "akka-contrib-mongodb-persistence-snapshot"
```

And in my build.sbt I've added the following.
```
val akkaVersion = "2.5.23"

libraryDependencies += "com.typesafe.akka" %% "akka-actor-typed" % akkaVersion
libraryDependencies += "com.typesafe.akka" %% "akka-persistence-typed" % akkaVersion
libraryDependencies += "com.typesafe.akka" %% "akka-http" % akkaHttpVersion
libraryDependencies +="com.github.scullxbones" %% "akka-persistence-mongo-casbah" % "2.2.9"

// Test libraries
libraryDependencies += "org.scalactic" %% "scalactic" % scalactic
libraryDependencies += "org.scalatest" %% "scalatest" % scalactic % "test"
libraryDependencies += "com.typesafe.akka" %% "akka-testkit" % akkaVersion % Test
libraryDependencies += "com.typesafe.akka" %% "akka-actor-testkit-typed" % akkaVersion % Test
 ```

I've tried everything including reading the source where the error is posted from and to be fair they dont seem to match.

**Comment by serishma-mallela** [comment]
@nmolenaar can you provide the fix for this issue.
