### ISSUE TITLE
Akka 2.4

### ISSUE THREAD

**Issue by twillouer** [scullxbones/akka-persistence-mongo#30]
Hi,

thanks a lot for the great work, it work like a charm !

Did you plain to release a new version for akka 2.4 ?
Some api moves and the akka-persistence-mongo cannot be used anymore :-(

**Comment by scullxbones** [comment]
Sure, that's the plan. I want to make sure that Mongo 3 is supported with the new driver versions first.

**Comment by twillouer** [comment]
Thanks, if I can help (for example, test a SNAPSHOT),  I will be delighted

**Comment by scullxbones** [comment]
Hi @twillouer -

I've pushed a snapshot `1.0.0-SNAPSHOT` to Sonatype.  I'm going to be writing docs for a little while with all of the changes, but if you're still interested in providing feedback on the snapshot, that would be great.

Make sure you have a resolver for `https://oss.sonatype.org/content/repositories/snapshots` in scope.

Thanks!

**Comment by twillouer** [comment]
Thanks, I'm already on it since 2 hours and it work like a charm for now :)

**Comment by scullxbones** [comment]
Great!  I've begun to update the docs, please let me know if you run into any problems with either the docs or the implementation.

**Comment by twillouer** [comment]
Hi,

I'm facing a new problem, and i'm not enough fluent in scala to resolve it (and it's late in my country :))

Perhaps it's a misconfiguration, but if you have any idea...

```
Uncaught error from thread [MyCluster-akka-contrib-persistence-dispatcher-26] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[MyCluster]
java.lang.AbstractMethodError: akka.contrib.persistence.mongodb.MongoJournal.akka$persistence$journal$AsyncWriteJournal$_setter_$akka$persistence$journal$AsyncWriteJournal$$config_$eq(Lcom/typesafe/config/Config;)V
        at akka.persistence.journal.AsyncWriteJournal$class.$init$(AsyncWriteJournal.scala:29)
        at akka.contrib.persistence.mongodb.MongoJournal.<init>(MongoJournal.scala:19)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at akka.util.Reflect$.instantiate(Reflect.scala:44)
        at akka.actor.NoArgsReflectConstructor.produce(Props.scala:357)
        at akka.actor.Props.newActor(Props.scala:259)
        at akka.actor.ActorCell.newActor(ActorCell.scala:561)
        at akka.actor.ActorCell.create(ActorCell.scala:587)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:460)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:482)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
21:49:30.841UTC MyCluster-akka-contrib-persistence-dispatcher-26 ERROR akka.actor.ActorSystemImpl  - Uncaught error from thread [MyCluster-akka-contrib-persistence-dispatcher-26] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.AbstractMethodError: akka.contrib.persistence.mongodb.MongoJournal.akka$persistence$journal$AsyncWriteJournal$_setter_$akka$persistence$journal$AsyncWriteJournal$$config_$eq(Lcom/typesafe/config/Config;)V
        at akka.persistence.journal.AsyncWriteJournal$class.$init$(AsyncWriteJournal.scala:29) ~[twillouer.jar:na]
        at akka.contrib.persistence.mongodb.MongoJournal.<init>(MongoJournal.scala:19) ~[twillouer.jar:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_66-internal]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_66-internal]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_66-internal]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_66-internal]
        at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_66-internal]
        at akka.util.Reflect$.instantiate(Reflect.scala:44) ~[twillouer.jar:na]
        at akka.actor.NoArgsReflectConstructor.produce(Props.scala:357) ~[twillouer.jar:na]
        at akka.actor.Props.newActor(Props.scala:259) ~[twillouer.jar:na]
        at akka.actor.ActorCell.newActor(ActorCell.scala:561) ~[twillouer.jar:na]
        at akka.actor.ActorCell.create(ActorCell.scala:587) ~[twillouer.jar:na]
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:460) ~[twillouer.jar:na]
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:482) ~[twillouer.jar:na]
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282) ~[twillouer.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:223) ~[twillouer.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66-internal]
21:49:30.843UTC MyCluster-akka.actor.default-dispatcher-3 DEBUG a.p.Persistence(akka://MyCluster)  - Create plugin: akka-contrib-mongodb-persistence-snapshot akka.contrib.persistence.mongodb.MongoSnapshots
Heap

```

I use maven :

```
INFO] +- org.scala-lang:scala-library:jar:2.11.7:compile
[INFO] +- com.typesafe:config:jar:1.3.0:compile
[INFO] +- nl.grons:metrics-scala_2.11:jar:3.5.1_a2.3:compile
[INFO] |  \- io.dropwizard.metrics:metrics-healthchecks:jar:3.1.2:compile
[INFO] +- io.dropwizard.metrics:metrics-core:jar:3.1.2:compile
[INFO] +- io.dropwizard.metrics:metrics-jvm:jar:3.1.2:compile
[INFO] +- io.dropwizard.metrics:metrics-graphite:jar:3.1.2:compile
[INFO] +- ch.qos.logback:logback-core:jar:1.1.3:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.1.3:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] +- com.typesafe.akka:akka-actor_2.11:jar:2.4.0-RC1:compile
[INFO] +- com.typesafe.akka:akka-cluster_2.11:jar:2.4.0-RC1:compile
[INFO] |  \- com.typesafe.akka:akka-remote_2.11:jar:2.4.0-RC1:compile
[INFO] |     +- io.netty:netty:jar:3.10.3.Final:compile
[INFO] |     \- org.uncommons.maths:uncommons-maths:jar:1.2.2a:compile
[INFO] +- com.typesafe.akka:akka-cluster-tools_2.11:jar:2.4.0-RC1:compile
[INFO] +- com.typesafe.akka:akka-cluster-sharding_2.11:jar:2.4.0-RC1:compile
[INFO] +- com.typesafe.akka:akka-cluster-metrics_2.11:jar:2.4.0-RC1:compile
[INFO] +- com.typesafe.akka:akka-contrib_2.11:jar:2.4.0-RC1:compile
[INFO] +- com.typesafe.akka:akka-stream-experimental_2.11:jar:1.0:compile
[INFO] |  \- org.reactivestreams:reactive-streams:jar:1.0.0:compile
[INFO] +- com.typesafe.akka:akka-http-core-experimental_2.11:jar:1.0:compile
[INFO] |  \- com.typesafe.akka:akka-parsing-experimental_2.11:jar:1.0:compile
[INFO] +- com.typesafe.akka:akka-http-spray-json-experimental_2.11:jar:1.0:compile
[INFO] |  \- io.spray:spray-json_2.11:jar:1.3.1:compile
[INFO] +- com.typesafe.akka:akka-http-experimental_2.11:jar:1.0:compile
[INFO] +- com.typesafe.akka:akka-slf4j_2.11:jar:2.4.0-RC1:compile
[INFO] +- com.typesafe.akka:akka-persistence_2.11:jar:2.4.0-RC1:compile
[INFO] |  \- com.google.protobuf:protobuf-java:jar:2.5.0:compile
[INFO] +- com.typesafe.akka:akka-persistence-query-experimental_2.11:jar:2.4.0-RC1:compile
[INFO] |  \- com.typesafe.akka:akka-testkit_2.11:jar:2.4.0-RC1:compile
[INFO] +- com.github.romix.akka:akka-kryo-serialization_2.11:jar:0.3.3:compile
[INFO] |  +- com.typesafe.akka:akka-kernel_2.11:jar:2.3.9:compile
[INFO] |  +- com.esotericsoftware:kryo:jar:3.0.0:compile
[INFO] |  |  +- com.esotericsoftware:reflectasm:jar:1.10.0:compile
[INFO] |  |  |  \- org.ow2.asm:asm:jar:4.2:compile
[INFO] |  |  +- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:compile
[INFO] |  \- net.jpountz.lz4:lz4:jar:1.3.0:compile
[INFO] +- com.github.scullxbones:akka-persistence-mongo-casbah_2.11:jar:1.0.0-SNAPSHOT:compile
[INFO] |  \- com.github.scullxbones:akka-persistence-mongo-common_2.11:jar:1.0.0-SNAPSHOT:compile
[INFO] +- org.mongodb:casbah_2.11:pom:2.8.1:compile
[INFO] |  +- org.mongodb:casbah-commons_2.11:jar:2.8.1:compile
[INFO] |  |  +- com.github.nscala-time:nscala-time_2.11:jar:1.0.0:compile
[INFO] |  |  |  +- joda-time:joda-time:jar:2.3:compile
[INFO] |  |  |  \- org.joda:joda-convert:jar:1.2:compile
[INFO] |  |  \- org.mongodb:mongo-java-driver:jar:2.13.1:compile
[INFO] |  +- org.mongodb:casbah-core_2.11:jar:2.8.1:compile
[INFO] |  +- org.mongodb:casbah-query_2.11:jar:2.8.1:compile
[INFO] |  \- org.mongodb:casbah-gridfs_2.11:jar:2.8.1:compile
```

The mongodb is already up when running.. Any idea ?

**Comment by twillouer** [comment]
forget it, I clean my .m2 repository from previous build and everything is now ok

**Comment by twillouer** [comment]
last question:

```
| 00:32:31.105UTC Cluster-akka.actor.default-dispatcher-36 WARN  a.c.s.PersistentShardCoordinator  - Rejected to persist event type [akka.cluster.sharding.ShardCoordinator$Internal$ShardRegionRegistered] with sequence number [1] for persistenceId [/sharding/userActorCoordinator] due to [Unimplemented deserialization of message with manifest [akka.cluster.sharding.ShardCoordinator$Internal$ShardRegionRegistered] in [akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer]].
```

I know akka cluster is now using protobuf (I use clustersharding with rememberentities=true), do you have the same error ?

```
00:32:31.093UTC Cluster-akka-contrib-persistence-dispatcher-32 DEBUG akka.actor.ActorSystemImpl  - Using EventAdapter: akka.persistence.journal.IdentityEventAdapter$ for event [akka.cluster.sharding.ShardCoordinator$Internal$ShardRegionRegistered]
00:32:31.100UTC Cluster-akka-contrib-persistence-dispatcher-33 DEBUG a.s.Serialization(akka://Cluster)  - Using serializer[akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer] for message [akka.cluster.sharding.ShardCoordinator$Internal$ShardRegionRegistered]
```

**Comment by scullxbones** [comment]
Hmm.  No I haven't seen this before.  I don't typically use Cluster or Cluster Sharding though, so that may not mean much.

I don't see this error happening inside of the journal plugin.  Do you see this issue with just the mongodb journal?  Or other journals as well (e.g. in-memory or level db)?

**Comment by scullxbones** [comment]
Tracking the `ClusterSharding` issue in #41
