### ISSUE TITLE
ClassNotFoundException on journal replay

### ISSUE THREAD

**Issue by pkudinov** [scullxbones/akka-persistence-mongo#45]
Hi!

I get 
```
[ERROR] [09/09/2015 14:16:41.784] [application-akka.actor.default-dispatcher-2] [akka://application/user/local-orders/order-id] Persistence failure when replaying events for persistenceId [order-id]. Last known sequence number [0]
java.lang.ClassNotFoundException: actors.OrderIdActor$Incremented$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at akka.contrib.persistence.mongodb.RxMongoSerializers$JournalDeserializer$.deserializePayload(RxMongoSerializers.scala:105)
        at akka.contrib.persistence.mongodb.RxMongoSerializers$JournalDeserializer$.deserializeVersionOne(RxMongoSerializers.scala:97)
        at akka.contrib.persistence.mongodb.RxMongoSerializers$JournalDeserializer$.deserializeDocument(RxMongoSerializers.scala:87)
        at akka.contrib.persistence.mongodb.RxMongoSerializers$JournalDeserializer$.deserializeDocument(RxMongoSerializers.scala:84)
        at akka.contrib.persistence.mongodb.MongoPersistenceDriver.deserializeJournal(MongoPersistence.scala:107)
        at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$1.applyOrElse(RxMongoJournaller.scala:38)
        at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$1.applyOrElse(RxMongoJournaller.scala:37)
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
        at scala.collection.immutable.Stream.collect(Stream.scala:435)
        at akka.contrib.persistence.mongodb.RxMongoJournaller.akka$contrib$persistence$mongodb$RxMongoJournaller$$unwind(RxMongoJournaller.scala:37)
        at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$3.apply(RxMongoJournaller.scala:34)
        at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$3.apply(RxMongoJournaller.scala:34)
        at reactivemongo.api.DefaultCursor$$anon$2.reactivemongo$api$DefaultCursor$$anon$$go$1(cursor.scala:332)
        at reactivemongo.api.DefaultCursor$$anon$2$$anonfun$foldWhile$2.apply(cursor.scala:335)
        at reactivemongo.api.DefaultCursor$$anon$2$$anonfun$foldWhile$2.apply(cursor.scala:335)
        at reactivemongo.api.DefaultCursor$$anon$2$$anonfun$foldBulks$2.apply(cursor.scala:313)
        at reactivemongo.api.DefaultCursor$$anon$2$$anonfun$foldBulks$2.apply(cursor.scala:311)
        at reactivemongo.api.DefaultCursor$$anon$2$FoldResponses$$anonfun$procResponses$1.apply(cursor.scala:455)
        at reactivemongo.api.DefaultCursor$$anon$2$FoldResponses$$anonfun$procResponses$1.apply(cursor.scala:454)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```
with `"com.github.scullxbones" % "akka-persistence-mongo-rxmongo_2.11" % "1.0.3"`

code for OrderIdActor object:
```scala
object OrderIdActor {
  sealed trait Command
  case object Increment extends Command

  sealed trait Event extends Serializable
  case class Incremented(value: Int = 1) extends Event

  def props = Props(new OrderIdActor)
  def name = "order-id"
}
```

Am I missing something in configuration?

**Comment by scullxbones** [comment]
Hi - no that doesn't sound like a configuration problem to me.  It raises 2 questions:

1. Is `OrderIdActor` inside of the `actors` package?
1. If so, are there any interesting classloader tricks that you're doing?  Possibly using `tomcat/lib` in tomcat rather than `WEB-INF/lib`?

**Comment by pkudinov** [comment]
Thanks for your reply!

1. Yes, it is in actors package
2. I don't really know how identify what is a trick :) I could only say that it is a fresh Play 2.4.2 application created with activator.

This is my build.sbt:
```
name := """order-service"""

version := "1.0"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.7"

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"
val akkaVersion = "2.4.0-RC2"

libraryDependencies ++= Seq(
  jdbc,
  cache,
  ws,
  "org.scalatest" % "scalatest_2.11" % "2.2.4" % Test,
  "org.scalamock" %% "scalamock-scalatest-support" % "3.2.2" % "test",
  "org.reactivemongo" %% "play2-reactivemongo" % "0.11.6.play24",
  "org.reactivemongo" %% "reactivemongo-extensions-json" % "0.11.6.play24",

  "com.typesafe.akka" %%  "akka-persistence" % akkaVersion,
  "com.typesafe.akka" %%  "akka-testkit" % akkaVersion,
  "com.github.scullxbones" % "akka-persistence-mongo-rxmongo_2.11" % "1.0.3",
  "org.iq80.leveldb"            % "leveldb"          % "0.7",
  "org.fusesource.leveldbjni"   % "leveldbjni-all"   % "1.8"
)

routesGenerator := InjectedRoutesGenerator

parallelExecution in Test := false
```

**Comment by scullxbones** [comment]
Ok understood - I will try my hand at duplicating based on that.  You're right - it should "just work".

**Comment by scullxbones** [comment]
Ah I can't believe I didn't notice this before.

I think you *may* be persisting a companion object as an event, when you mean to persist the case class.  If so, it may have to do with your pattern matching approach.  

Can you share your `PersistentActor` implementation?  At a minimum the `receiveCommand` method should shed some light.

**Comment by pkudinov** [comment]
That's what I was doing at very beginning following recommendations from Akka in Action book. But later I've changed it.

Here is the function you are asking for:
```scala
  override def receiveCommand: Receive = {
    case Increment => persist(Incremented(1)){
      e =>
        updateState(e)
        sender() ! curId
    }
  }
```

Here is the case class declaration:
```scala
object OrderIdActor {
  sealed trait Command
  case object Increment extends Command

  sealed trait Event
  case class Incremented(value: Int = 1) extends Event

  def props = Props(new OrderIdActor)
  def name = "order-id"
}
```

**Comment by scullxbones** [comment]
So is it possible that the old event is still in the journal?  Or are you cleaning the journal before running your test?  If you look at the journal in the mongo console, can you see that string?  "OrderIdActor$Incremented$"

That receive command method looks fine to me.  I thought you might have been putting simply `Incremented` with no method parameters in it. The trailing $ on the error message above suggests a companion object instead of a serialized case class

**Comment by pkudinov** [comment]
Yes, I'm cleaning it every time before the run.

I even moved these events out of the class, to the package level and rerun again. No difference.

**Comment by pkudinov** [comment]
>The trailing $ on the error message above suggests a companion object instead of a serialized case class

Yes, now I've changed it and I'm getting `java.lang.ClassNotFoundException: actors.Incremented`

**Comment by scullxbones** [comment]
I was unable to duplicate with my understanding of the problem - can you take a look at the commit I referenced here and let me know if it correctly models the issue you are seeing?

**Comment by pkudinov** [comment]
Thank you so much for your effort. I've copied your test to my project and replaced your implementation of actors with mine. Test is green. I've even replaced embedded mongo with local database.

Then I've started the app with `activator run` and got the same exception.

So I guess the problem is somewhere in classloader. So I've copied these lines 
```
val cls = Class.forName("actors.Incremented").asInstanceOf[Class[X forSome {type X <: AnyRef}]]
Logger.info("Found class: " + cls)
```
into my `OrderIdActor`. The class is found without any problems. But it couldn't be found during journal replay:

```
$activator -jvm-debug 10021 -Dhttp.port=10020 ~run
Listening for transport dt_socket at address: 10021
[info] Loading project definition from /Users/pavel/sources/order-service/project
[info] Set current project to order-service (in build file:/Users/pavel/sources/order-service/)

--- (Running the application, auto-reloading is enabled) ---

[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:10020

(Server started, use Ctrl+D to stop and go back to the console...)

[success] Compiled in 935ms
[info] - play.api.libs.concurrent.ActorSystemProvider - Starting application default Akka system: application
[info] - application - Found class: class actors.Incremented
[info] - play.api.Play - Application started (Dev)
[ERROR] [09/19/2015 01:00:31.544] [application-akka.actor.default-dispatcher-3] [akka://application/user/local-orders/order-id] Persistence failure when replaying events for persistenceId [order-id]. Last known sequence number [10]
java.lang.ClassNotFoundException: actors.Incremented
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at akka.contrib.persistence.mongodb.RxMongoSerializers$JournalDeserializer$.deserializePayload(RxMongoSerializers.scala:105)
        at akka.contrib.persistence.mongodb.RxMongoSerializers$JournalDeserializer$.deserializeVersionOne(RxMongoSerializers.scala:97)
        at akka.contrib.persistence.mongodb.RxMongoSerializers$JournalDeserializer$.deserializeDocument(RxMongoSerializers.scala:87)
        at akka.contrib.persistence.mongodb.RxMongoSerializers$JournalDeserializer$.deserializeDocument(RxMongoSerializers.scala:84)
        at akka.contrib.persistence.mongodb.MongoPersistenceDriver.deserializeJournal(MongoPersistence.scala:107)
        at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$1.applyOrElse(RxMongoJournaller.scala:38)
        at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$1.applyOrElse(RxMongoJournaller.scala:37)
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
        at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
        at scala.collection.immutable.Stream.collect(Stream.scala:435)
        at akka.contrib.persistence.mongodb.RxMongoJournaller.akka$contrib$persistence$mongodb$RxMongoJournaller$$unwind(RxMongoJournaller.scala:37)
        at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$3.apply(RxMongoJournaller.scala:34)
        at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$3.apply(RxMongoJournaller.scala:34)
        at reactivemongo.api.DefaultCursor$$anon$2.reactivemongo$api$DefaultCursor$$anon$$go$1(cursor.scala:332)
        at reactivemongo.api.DefaultCursor$$anon$2$$anonfun$foldWhile$2.apply(cursor.scala:335)
        at reactivemongo.api.DefaultCursor$$anon$2$$anonfun$foldWhile$2.apply(cursor.scala:335)
        at reactivemongo.api.DefaultCursor$$anon$2$$anonfun$foldBulks$2.apply(cursor.scala:313)
        at reactivemongo.api.DefaultCursor$$anon$2$$anonfun$foldBulks$2.apply(cursor.scala:311)
        at reactivemongo.api.DefaultCursor$$anon$2$FoldResponses$$anonfun$procResponses$1.apply(cursor.scala:455)
        at reactivemongo.api.DefaultCursor$$anon$2$FoldResponses$$anonfun$procResponses$1.apply(cursor.scala:454)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by scullxbones** [comment]
Ah ok, so maybe some activator "magic" is going on.  :smile: 

I can look at this a bit later, but a quick search yielded this link - can you try it out and let me know if it helps?

http://stackoverflow.com/questions/24593120/classnotfoundexception-in-play-application-with-typesafe-activator

**Comment by pkudinov** [comment]
OMG, `activator start` did the trick. Thank you so much! But that is really unexpected behaviour :(

**Comment by scullxbones** [comment]
Great!  Happy to help.  I'll add this to the docs, thanks for submitting!
