### ISSUE TITLE
NullpointerException when accessing currentEventsByPersistenceId

### ISSUE THREAD

**Issue by toggm** [scullxbones/akka-persistence-mongo#61]
With an empty journal I try to access the new currentEventsByPersistenceId the following way:

```
val readJournal = PersistenceQuery(context.system).readJournalFor[ScalaDslMongoReadJournal](MongoReadJournal.Identifier)
val source: Source[EventEnvelope, Unit] = readJournal.currentEventsByPersistenceId(persistenceId, 0, Long.MaxValue)
implicit val mat = ActorMaterializer()
source.runForeach { event => 
    log.error(s"EVENT: sevent")
    if (event != null && event.event != null) {
      receive(event.event)
    }
  }
```

When starting the application I receive the following NullPointerException:
```
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
	at akka.actor.ActorCell.create(ActorCell.scala:605)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:460)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:482)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
	at reactivemongo.bson.buffer.WritableBuffer$class.writeString(buffer.scala:71)
	at reactivemongo.core.netty.ChannelBufferWritableBuffer.writeString(netty.scala:59)
	at reactivemongo.bson.buffer.DefaultBufferHandler$BSONStringBufferHandler$.write(bufferhandlers.scala:83)
	at reactivemongo.bson.buffer.DefaultBufferHandler$BSONStringBufferHandler$.write(bufferhandlers.scala:82)
	at reactivemongo.bson.buffer.DefaultBufferHandler$.serialize(bufferhandlers.scala:226)
	at reactivemongo.bson.buffer.DefaultBufferHandler$BSONDocumentBufferHandler$$anonfun$write$1.apply(bufferhandlers.scala:93)
	at reactivemongo.bson.buffer.DefaultBufferHandler$BSONDocumentBufferHandler$$anonfun$write$1.apply(bufferhandlers.scala:90)
	at scala.collection.immutable.Stream.foreach(Stream.scala:594)
	at reactivemongo.bson.buffer.DefaultBufferHandler$BSONDocumentBufferHandler$.write(bufferhandlers.scala:90)
	at reactivemongo.bson.buffer.DefaultBufferHandler$BSONDocumentBufferHandler$.write(bufferhandlers.scala:86)
	at reactivemongo.bson.buffer.DefaultBufferHandler$.serialize(bufferhandlers.scala:226)
	at reactivemongo.bson.buffer.DefaultBufferHandler$.writeDocument(bufferhandlers.scala:241)
	at reactivemongo.api.BSONSerializationPack$.writeToBuffer(serializationpack.scala:64)
	at reactivemongo.api.BSONSerializationPack$.writeToBuffer(serializationpack.scala:41)
	at reactivemongo.api.collections.GenericQueryBuilder$class.reactivemongo$api$collections$GenericQueryBuilder$$write(genericquerybuilder.scala:61)
	at reactivemongo.api.collections.GenericQueryBuilder$class.defaultCursor(genericquerybuilder.scala:85)
	at reactivemongo.api.collections.GenericQueryBuilder$class.cursor(genericquerybuilder.scala:81)
	at reactivemongo.api.collections.bson.BSONQueryBuilder.cursor(bsoncollection.scala:78)
	at akka.contrib.persistence.mongodb.EventsByPersistenceId.initial(RxMongoReadJournaller.scala:138)
	at akka.contrib.persistence.mongodb.IterateeActorPublisher$class.preStart(RxMongoReadJournaller.scala:20)
	at akka.contrib.persistence.mongodb.EventsByPersistenceId.preStart(RxMongoReadJournaller.scala:113)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
	at akka.contrib.persistence.mongodb.EventsByPersistenceId.akka$stream$actor$ActorPublisher$$super$aroundPreStart(RxMongoReadJournaller.scala:113)
	at akka.stream.actor.ActorPublisher$class.aroundPreStart(ActorPublisher.scala:322)
	at akka.contrib.persistence.mongodb.EventsByPersistenceId.aroundPreStart(RxMongoReadJournaller.scala:113)
	at akka.actor.ActorCell.create(ActorCell.scala:589)
```

What am I missing?

**Comment by scullxbones** [comment]
I don't think you're missing anything.  I also don't think that case has been tested to date - the tests focus on journals that have data in them.

I'll have to look into it to see what's going on, although I am a bit surprised that an empty journal would cause an NPE - it should cause an empty cursor.  If you are in a hurry, you could try the casbah driver.

**Comment by scullxbones** [comment]
So the really weird thing is that this is a cursor generated by a query - meaning that this code should only run if there are some results for the query (`persistenceId`,0,`MaxValue`).

I did some preliminary testing, and I don't see an NPE from the `ReadJournal` on an empty journal query.  Is there any other relevant information as far as helping me to reproduce the issue?  For example, how are you confirming that the journal is empty?  `db.akka_persistence_journal.count()` run in the mongo console should be 0.

**Comment by alari** [comment]
BTW, journal upgrades in 100 messages batches. If you have >100 messages, you should run journal upgrade several times :)

I noticed the similar issue when ran journal upgrade on production :) it was awful. But logs helped -- plugin mentions about the number of unprocessed messages on launch.

**Comment by toggm** [comment]
Ok, you're right. I started with an empty journal, but this Exception rises when the application stores its first event in the journal using a PersistentActor and afterwards tries to read that event from journal.
I tried also to store the event using the default Java serializer.

I've prepared an example within my application. You may checkout the LAS-1_rxmongo_nullpointer in the following project:
https://github.com/tegonal/lasius/tree/dev/LAS-1_rxmongo_nullpointer

Start the application with "activator run". After connecting to localhost:9000 you may login using the following credentials:
email:noob@test.com
password:noob

The db will get initalized with default data. After login you should see the exception in the applications log.

Thanks.

**Comment by scullxbones** [comment]
> BTW, journal upgrades in 100 messages batches. If you have >100 messages, you should run journal upgrade several times :)

Dammit.  Sorry about that @alari - I checked and I switched the journal itself back to Iteratees, but the upgrade is still on the new-as-of 0.11 `foldWhile` that burned me in the journal with the blocks-of-100 thing.  I'll add another ticket to fix.

@toggm - thank you!  I'll grab that soon.  This will help a lot as far as duplication.

**Comment by scullxbones** [comment]
Ok I pulled it down and was able to reproduce the NPE.  There wasn't much information here, so I dug a little deeper and ran this test case in a debugger.

What I saw was that `persistenceId` is null here:

```scala
abstract class PersistenceViewWrapper extends Actor with ActorLogging {
  val persistenceId: String

  val readJournal = PersistenceQuery(context.system).readJournalFor[ScalaDslMongoReadJournal](MongoReadJournal.Identifier)
```

So I'm thinking that `ReactiveMongo` blows up when it tries to build out the query object.  I'm closing this issue for now, as I'm sure that you aren't trying to use a null `persistenceId`.  If an issue persists after the null value is fixed, please let me know and we'll track it.  Thanks!

**Comment by toggm** [comment]
Brian, thanks for having a look at it. I didn't have time to fix the implementation and check the upgrade but will post the answer here as soon as I've succeeded.

**Comment by scullxbones** [comment]
Sure thing - I think you're getting burned by early initialization with the `val persistenceId`.  Will it work as a `def`?.  Let me know if anything comes up!
