### ISSUE TITLE
NoClassDefFoundError with reactivemongo and 0.4.2

### ISSUE THREAD

**Issue by Jacoby6000** [scullxbones/akka-persistence-mongo#65]
We're using these dependencies

```scala
        val reactiveMongo = "org.reactivemongo"            %% "reactivemongo"                   % "0.10.5.0.akka23"
        val akkaPersistDb = "com.github.scullxbones"       %%  "akka-persistence-mongo-rxmongo" % "0.4.2" 
```

And getting the error below (repeating) on startup of our application. 

```
Uncaught error from thread [test-akka-contrib-persistence-dispatcher-25Uncaught error from thread [test-akka-contrib-persistence-dispatcher-27] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[test]
]
java.lang.NoClassDefFoundError: reactivemongo/api/collections/bson/package$BSONCollectionProducer$
	at akka.contrib.persistence.mongodb.RxMongoPersistenceDriver$class.collection(RxMongoPersistenceExtension.scala:66)
	at akka.contrib.persistence.mongodb.RxMongoDriver.collection(RxMongoPersistenceExtension.scala:72)
	at akka.contrib.persistence.mongodb.RxMongoSnapshotter.snaps(RxMongoPersistenceSnapshotter.scala:95)
	at akka.contrib.persistence.mongodb.RxMongoSnapshotter.findYoungestSnapshotByMaxSequence(RxMongoPersistenceSnapshotter.scala:72)
	at akka.contrib.persistence.mongodb.RxMongoPersistenceExtension$$anon$2.akka$contrib$persistence$mongodb$MongoPersistenceSnapshotFailFast$$super$findYoungestSnapshotByMaxSequence(RxMongoPersistenceExtension.scala:85)
	at akka.contrib.persistence.mongodb.MongoPersistenceSnapshotFailFast$$anonfun$findYoungestSnapshotByMaxSequence$1.apply(MongoSnapshots.scala:87)
	at akka.contrib.persistence.mongodb.MongoPersistenceSnapshotFailFast$$anonfun$findYoungestSnapshotByMaxSequence$1.apply(MongoSnapshots.scala:87)
	at akka.pattern.CircuitBreaker$State$class.callThrough(CircuitBreaker.scala:295)
	at akka.pattern.CircuitBreaker$Closed$.callThrough(CircuitBreaker.scala:344)
	at akka.pattern.CircuitBreaker$Closed$.invoke(CircuitBreaker.scala:353)
	at akka.pattern.CircuitBreaker.withCircuitBreaker(CircuitBreaker.scala:113)
	at akka.contrib.persistence.mongodb.MongoPersistenceSnapshotFailFast$class.findYoungestSnapshotByMaxSequence(MongoSnapshots.scala:87)
	at akka.contrib.persistence.mongodb.RxMongoPersistenceExtension$$anon$2.findYoungestSnapshotByMaxSequence(RxMongoPersistenceExtension.scala:85)
	at akka.contrib.persistence.mongodb.MongoSnapshots.loadAsync(MongoSnapshots.scala:23)
	at akka.persistence.snapshot.SnapshotStore$$anonfun$receive$1.applyOrElse(SnapshotStore.scala:27)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.contrib.persistence.mongodb.MongoSnapshots.aroundReceive(MongoSnapshots.scala:11)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: reactivemongo.api.collections.bson.package$BSONCollectionProducer$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
```

I wasn't able to find anywhere that you're referencing "reactivemongo/api/collections/bson/package$BSONCollectionProducer$" so I don't know what the deal is. But i do believe that [the path specified there](https://github.com/ReactiveMongo/ReactiveMongo/blob/70e3e476870ae5a8487d625d1a6028cb74268825/driver/src/main/scala/api/collections/bson/bsoncollection.scala) is correct.

**Comment by scullxbones** [comment]
Hi & thanks for the report

Please make sure to also add the `reactivemongo-bson` dependency as well.  This is a reactivemongo requirement:
```
"org.reactivemongo"            %% "reactivemongo-bson"                   % "0.10.5.0.akka23"
```

Let me know if that solves your issue.

**Comment by Jacoby6000** [comment]
I get the same problem even after adding that dependency. It might be worth noting that this worked before, when I was using 0.3.0

**Comment by scullxbones** [comment]
Ah!  So sorry, been a while since i've been in that codebase.  `0.4` is not compatible with rxmongo `0.10` series.  You'll need to upgrade to the `0.11.x` driver.

**Comment by scullxbones** [comment]
Yep mentioned in the changelog in [README](https://github.com/scullxbones/akka-persistence-mongo/blob/akka23/README.md).  Sorry should have remembered that initially.
