### ISSUE TITLE
NoSuchMethodException when using RxMongo 0.12.0

### ISSUE THREAD

**Issue by ticofab** [scullxbones/akka-persistence-mongo#83]
Hi, and thanks for this tool! Unfortunately, using the 1.1.5 version with RxMongo, I get this exception. Is it only my problem? Cheers

```
[error] - akka.actor.ActorSystemImpl - Uncaught fatal error from thread [application-akka-contrib-persistence-dispatcher-11] shutting down ActorSystem [application]
java.lang.NoSuchMethodError: reactivemongo.api.MongoConnection.waitForPrimary(Lscala/concurrent/duration/FiniteDuration;)Lscala/concurrent/Future;
        at akka.contrib.persistence.mongodb.RxMongoDriver.waitForPrimary(RxMongoPersistenceExtension.scala:62) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoDriver.akka$contrib$persistence$mongodb$RxMongoDriver$$unauthenticatedConnection$lzycompute(RxMongoPersistenceExtension.scala:53) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoDriver.akka$contrib$persistence$mongodb$RxMongoDriver$$unauthenticatedConnection(RxMongoPersistenceExtension.scala:50) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoDriver$$anonfun$connection$2.apply(RxMongoPersistenceExtension.scala:57) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoDriver$$anonfun$connection$2.apply(RxMongoPersistenceExtension.scala:56) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at scala.Option.fold(Option.scala:158) ~[scala-library-2.11.7.jar:na]
        at akka.contrib.persistence.mongodb.RxMongoDriver.connection$lzycompute(RxMongoPersistenceExtension.scala:56) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoDriver.connection(RxMongoPersistenceExtension.scala:54) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoDriver.db(RxMongoPersistenceExtension.scala:152) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoDriver.collection(RxMongoPersistenceExtension.scala:154) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoSnapshotter.snaps(RxMongoSnapshotter.scala:47) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoSnapshotter.findYoungestSnapshotByMaxSequence(RxMongoSnapshotter.scala:20) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoPersistenceExtension$Configured$$anon$2.akka$contrib$persistence$mongodb$MongoPersistenceSnapshotFailFast$$super$findYoungestSnapshotByMaxSequence(RxMongoPersistenceExtension.scala:181) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.MongoPersistenceSnapshotFailFast$$anonfun$findYoungestSnapshotByMaxSequence$1.apply(MongoSnapshots.scala:89) ~[akka-persistence-mongo-common_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.MongoPersistenceSnapshotFailFast$$anonfun$findYoungestSnapshotByMaxSequence$1.apply(MongoSnapshots.scala:89) ~[akka-persistence-mongo-common_2.11-1.0.9.jar:1.0.9]
        at akka.pattern.CircuitBreaker$State$class.materialize$1(CircuitBreaker.scala:298) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.pattern.CircuitBreaker$State$class.callThrough(CircuitBreaker.scala:315) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.pattern.CircuitBreaker$Closed$.callThrough(CircuitBreaker.scala:363) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.pattern.CircuitBreaker$Closed$.invoke(CircuitBreaker.scala:371) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.pattern.CircuitBreaker.withCircuitBreaker(CircuitBreaker.scala:115) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.contrib.persistence.mongodb.MongoPersistenceSnapshotFailFast$class.findYoungestSnapshotByMaxSequence(MongoSnapshots.scala:89) ~[akka-persistence-mongo-common_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.RxMongoPersistenceExtension$Configured$$anon$2.findYoungestSnapshotByMaxSequence(RxMongoPersistenceExtension.scala:181) ~[akka-persistence-mongo-rxmongo_2.11-1.0.9.jar:1.0.9]
        at akka.contrib.persistence.mongodb.MongoSnapshots.loadAsync(MongoSnapshots.scala:25) ~[akka-persistence-mongo-common_2.11-1.0.9.jar:1.0.9]
        at akka.persistence.snapshot.SnapshotStore$$anonfun$1$$anonfun$applyOrElse$5.apply(SnapshotStore.scala:37) ~[akka-persistence_2.11-2.4.0.jar:na]
        at akka.persistence.snapshot.SnapshotStore$$anonfun$1$$anonfun$applyOrElse$5.apply(SnapshotStore.scala:37) ~[akka-persistence_2.11-2.4.0.jar:na]
        at akka.pattern.CircuitBreaker$State$class.materialize$1(CircuitBreaker.scala:298) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.pattern.CircuitBreaker$State$class.callThrough(CircuitBreaker.scala:315) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.pattern.CircuitBreaker$Closed$.callThrough(CircuitBreaker.scala:363) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.pattern.CircuitBreaker$Closed$.invoke(CircuitBreaker.scala:371) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.pattern.CircuitBreaker.withCircuitBreaker(CircuitBreaker.scala:115) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.persistence.snapshot.SnapshotStore$$anonfun$1.applyOrElse(SnapshotStore.scala:37) ~[akka-persistence_2.11-2.4.0.jar:na]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.7.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.contrib.persistence.mongodb.MongoSnapshots.aroundReceive(MongoSnapshots.scala:13) ~[akka-persistence-mongo-common_2.11-1.0.9.jar:1.0.9]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:494) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.0.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
```

**Comment by scullxbones** [comment]
Hi @ticofab,

It looks like the reactive mongo team has made a backward-incompatible change in `0.12`.  Can you stick to `0.11.x` version?

Eventually I'll look to support `0.12`, but I don't plan on supporting snapshots at any point.

Thanks!

**Comment by ticofab** [comment]
Thanks for the quickest reply, @scullxbones ! It seems to me that RxMongo 0.11.9 is already breaking, there are troubles with the waitForPrimary method. The last working version seems to be 0.11.7.play24. Do you see the same?

**Comment by scullxbones** [comment]
Wow, that's frustrating, sorry.  I assumed they were being careful about backward compatibility within major release (`0.11`).  I think the last version I used was `0.11.6`.

**Comment by scullxbones** [comment]
Also - I see you're using `1.0.9` of the plugin.  The latest of this plugin is now `1.1.5`, check it out when you get a chance.  I don't think it will fix this problem though.

**Comment by ticofab** [comment]
Indeed I tried - 1.1.5 has the same issue with waitForPrimary. I have another nice topic to discuss, will open it in another issue :)

**Comment by scullxbones** [comment]
Ok.  Let me make this issue a documentation ticket - max supported rxmongo version.

Thanks for reporting!

**Comment by scullxbones** [comment]
Docs updated
